- name: Zip firmware
  run: |
    mkdir artifacts
    cp build/*/zephyr/*.uf2 artifacts/
    zip -r firmware.zip artifacts

- name: Upload firmware
  uses: actions/upload-artifact@v4
  with:
    name: firmware
    path: firmware.zip
