CONFIG_ZMK_POINTING=y
CONFIG_NFCT_PINS_AS_GPIOS=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_MOUSE=y


CONFIG_SPI=y
CONFIG_INPUT=y


CONFIG_PMW3610=y
CONFIG_PMW3610_INVERT_X=n
CONFIG_PMW3610_SMART_ALGORITHM=y
CONFIG_PMW3610_REPORT_INTERVAL_MIN=1

# スリープまでの時間を延ばす
CONFIG_ZMK_IDLE_TIMEOUT=0

# RUN→RESTへの遷移（RUNは最大でも 3264ms まで）
CONFIG_PMW3610_RUN_DOWNSHIFT_TIME_MS=3264

# 深いRESTに落ちるまでを “数分” にする（オーバーフロー回避）
CONFIG_PMW3610_REST1_DOWNSHIFT_TIME_MS=600000     # 10分
CONFIG_PMW3610_REST2_DOWNSHIFT_TIME_MS=600000     # 10分

# REST中のサンプル周期は “ほどほど” に（最小10msは避ける）
CONFIG_PMW3610_REST1_SAMPLE_TIME_MS=40           # デフォ同等
CONFIG_PMW3610_REST2_SAMPLE_TIME_MS=80
CONFIG_PMW3610_REST3_SAMPLE_TIME_MS=120


CONFIG_ZMK_BATTERY_REPORTING=y
